version: '3.8'

services:

  db:
    restart: "no"
    environment:
      BUILD_TYPE: "DEV" 

  adminer:
    restart: "no"
    environment:
      BUILD_TYPE: "DEV"

    # environment:
    #   ADMINER_DEFAULT_SYSTEM: pgsql
    #   ADMINER_DEFAULT_SERVER: postgres
    #   ADMINER_DEFAULT_DATABASE: ${DATABASE_DB}

    networks:
      - back

  rabbit:
    environment:
      BUILD_TYPE: "DEV" 

    ports:
      - "9999:15672"

  back:
    environment:
      BUILD_TYPE: "DEV" 
      ENV: 'DEV'

    restart: "no"

    stdin_open:  true # docker run -i
    tty: true        # docker run -t

    # volumes:
    #   - ./api:/app

  api:
    restart: "no"
    environment:
      BUILD_TYPE: "DEV" 

    stdin_open:  true # docker run -i
    tty: true        # docker run -t

  front:
    restart: "no"
    environment:
      BUILD_TYPE: "DEV" 

    stdin_open:  true # docker run -i
    tty: true        # docker run -t

    # ports:
    #   - "3000:3000"

    # volumes:
    #   - ./site:/app


  nginx:
    restart: "no"
    environment:
      BUILD_TYPE: "DEV" 

    stdin_open:  true # docker run -i
    tty: true        # docker run -t


    ports:
      - "8080:80"


