FROM node:18-alpine3.16 AS build

WORKDIR /app

COPY site .

RUN yarn install
RUN (cd node_modules/react-gauge-chart && npm i lodash.isequal)
RUN yarn build


FROM nginx

COPY _build/nginx/local-prod.conf /etc/nginx/conf.d/default.conf

RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/dist /usr/share/nginx/html

WORKDIR /usr/share/nginx/html



CMD ["/bin/sh", "-c", "nginx -g \"daemon off;\""]